GET http://localhost:8081/api/products/insert
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICI1OGMyMGQwNy1kOTQyLTRkOTMtOWQwOC02MmJlMDI2YWM5YmIifQ.eyJleHAiOjE3MzE2NzUyNDIsImlhdCI6MTczMTY3MzQ0MiwianRpIjoiOTI4ZDc1YmMtMmYwOS00YTQ5LTlhMDQtODk5MjhhODkyOWIyIiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MTgwL3JlYWxtcy90ZXN0IiwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdDo4MTgwL3JlYWxtcy90ZXN0Iiwic3ViIjoiZTg1YjgxN2UtMmYyMS00YTM1LWE5NWMtYmZhMWJkNTE3Yjc0IiwidHlwIjoiUmVmcmVzaCIsImF6cCI6Im15Y2xpZW50Iiwic2lkIjoiMWYyN2RkZWMtZmIwNC00OTQ4LTk2ZjMtZGRkODhmMjUzMDA4Iiwic2NvcGUiOiJlbWFpbCBwcm9maWxlIGFjciBiYXNpYyB3ZWItb3JpZ2lucyByb2xlcyJ9.o58D6HeGaHe5-A_TRXp0NUJ7X6HFHFNwvYbXLl2EYJkaYQa4J3uBR5gQc8jtcn_Xfd0wfMjL17q-PZ4Neq8gUQ